project:
  type: book

engine: jupyter

book:
  title: "OBITools V4"
  author: "Eric Coissac"
  date: "1/17/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - formats.qmd
    - tutorial.qmd
    - commands.qmd
    - library.qmd
    - annexes.qmd
    - references.qmd

bibliography: book.bib

execute: 
  freeze: auto

format:
  html:
    theme: zephyr
  pdf:
    documentclass: scrreprt
  epub: default





